#datasource:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost/ssafy-sns
#  username:
#  password:

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sns
      authenticaion-database: admin
  batch:
    job:
      enabled: false
jwt:
  header: Authorization
  secret: ssafy
  token-validity-in-seconds: 86400

api:
  contest:
    servicekey: fa6c5efa2a0747fe9c047f5af687869d
    url: http://kopis.or.kr/openApi/restful/pblprfr


frontend:
  alarm:
    post: 글
    postPath: /posts/

    comment: 댓글
    commentPath: /comments/

    likePost: 좋아요
    likePostPath: /likePost/