#datasource:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost/ssafy-sns
#  username:
#  password:

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sns
      username: root
      password: example
      authenticaion-database: admin
  batch:
    job:
      enabled: false
jwt:
  header: Authorization
  secret: ssafy
  token-validity-in-seconds: 86400
db:
  uri: mongodb://localhost:27017
  db-name: sns
