#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/ssafy-sns
#    username:
#    password:

jwt:
  header: Authorization
  secret: ssafy
  token-validity-in-seconds: 86400