version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-storage:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  jenkins:
    image: jenkins/jenkins
    ports:
      - "9090:8080"
    privileged: true
    user: root
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80