version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-storage:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  jenkins:
    image: jenkins/jenkins
    ports:
      - "9090:8080"
    privileged: true
    user: root
